In [2]:
import numpy as np

In [ ]:
# Create a NumPy array containing numbers 1–10.
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Create an array of monthly revenue.
price = np.array([100, 200, 300,400])
qty = np.array([10,10,10,10])
rev = price * qty
print(rev)

[1000 2000 3000 4000]


In [5]:
# Multiply all elements of an array by 5.
price = np.array([100, 200, 300,400])
print(price * 5)

[ 500 1000 1500 2000]


In [8]:
# Create a 2D array for student marks.
# PCM marks
arr = np.array([
    [75,80,90],
    [78,95,45]
    ])
print(arr)

[[75 80 90]
 [78 95 45]]


In [9]:
# Convert a Python list into a NumPy array.
lst = [15,48,96,48]
arr = np.array([lst])
print(arr)

[[15 48 96 48]]


In [11]:
# Increase all values of an array by 10%.
arr = np.array([100, 200, 300,400])
arr1 = arr + (arr * 0.10)
print(arr1)

[110. 220. 330. 440.]


In [13]:
# Create an array of temperatures.
cel = np.array([0,20,50,100])
feh = (cel * 1.8) + 32
print("temprature in cel",cel)
print("temprature in feh",feh)

temprature in cel [  0  20  50 100]
temprature in feh [ 32.  68. 122. 212.]


In [16]:
# Subtract 2 from each element of an array.
arr1 = np.array([100, 200, 300,400])
arr2 = arr1  - 2
print(arr1, "\nafter subtracting 2 \n",arr2)

[100 200 300 400] 
after subtracting 2 
 [ 98 198 298 398]


In [19]:
# Create a 3x3 array manually.
arr = np.array([[
    [75,80,90],
    [78,95,45],
    [15,48,69]
    ],
    
    [
    [75,80,90],
    [78,95,45],
    [15,48,69]
    ],
    [
    [75,80,90],
    [78,95,45],
    [15,48,69]
    ]
    ])

print(arr)

[[[75 80 90]
  [78 95 45]
  [15 48 69]]

 [[75 80 90]
  [78 95 45]
  [15 48 69]]

 [[75 80 90]
  [78 95 45]
  [15 48 69]]]


In [23]:
# Compare list multiplication vs NumPy multiplication.
lst = [10,15,20]
arr = np.array([10,15,20])

print("-" * 30)
print("for list")
print(lst*3)
print("print list 3 times")
print("to do multiplication use for loop \n for loop output:")
for i in lst:
    print(i * 3)

print("-" * 30)
print("for numpy")
print(arr * 3)

------------------------------
for list
[10, 15, 20, 10, 15, 20, 10, 15, 20]
print list 3 times
to do multiplication use for loop 
 for loop output:
30
45
60
------------------------------
for numpy
[30 45 60]


In [26]:
# Create an array using np.arange(1,50).
arr =  np.arange(1,50)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [28]:
# Generate 20 evenly spaced numbers between 10 and 100.
arr = np.linspace(10,100,20)
print(arr)

[ 10.          14.73684211  19.47368421  24.21052632  28.94736842
  33.68421053  38.42105263  43.15789474  47.89473684  52.63157895
  57.36842105  62.10526316  66.84210526  71.57894737  76.31578947
  81.05263158  85.78947368  90.52631579  95.26315789 100.        ]


In [31]:
# Create a 4×4 zero matrix.
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
# Create a 3×3 identity matrix.
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Generate 10 random integers between 1–100.
arr = np.random.randint(1,100,10)
print(arr)

[72 76 73 85 14 69 70 34  6 80]


In [ ]:
# Generate 15 random numbers between 0–1.
arr = np.random.rand(15)
print(arr)

[0.92854942 0.74263563 0.55125566 0.83336392 0.64317662 0.29015058
 0.91866554 0.67501408 0.77390797 0.97276915 0.52676317 0.74651246
 0.83244378 0.83844167 0.45714974]


In [42]:
# Create a 5×5 matrix of ones.
arr = np.ones((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Generate random ratings (1–5) for 50 customers.
ratings = [np.random.randint(1, 5) for _ in range(50)]
print(ratings)

[3, 3, 3, 2, 4, 1, 4, 4, 1, 3, 2, 1, 4, 2, 2, 1, 2, 4, 4, 1, 4, 2, 3, 1, 2, 2, 4, 1, 1, 4, 1, 3, 3, 4, 3, 2, 1, 3, 4, 2, 2, 4, 3, 1, 4, 1, 3, 2, 3, 2]


In [ ]:
# Use np.random.seed() to reproduce results.
np.random.seed(3)
arr = np.random.randint(1,10,2)
print(arr)

[9 4]


In [ ]:
# Create a logarithmic array using np.logspace().
arr = np.logspace(1,3,2)
print(arr)

[  10. 1000.]


Mini Project 1 — Sales Data Generator
Create dataset using NumPy.
Tasks
1 Create 30 random sales values
Range
1000 – 5000
2 Calculate
•	average sales 
•	maximum sales 
•	minimum sales 

In [ ]:
arr = np.random.randint(1000,5000,30)
print(arr)
print("Average:",np.mean(arr))
print("Maximum value:",np.max(arr))
print("Minimun value:",np.min(arr))

[4653 3920 1622 2633 3461 2642 4224 3555 1830 3567 4064 4243 4617 3427
 2359 1176 2829 4092 3910 3609 2429 1383 2742 4572 2564 4959 2590 2024
 1704 4049]
Average: 3181.633333333333
Maximum value: 4959
Minimun value: 1176


Mini Project 2 — Temperature Simulation
Generate
365 days temperature data
Range
15°C – 45°C
Tasks
1 Find average temperature
2 Find hottest day
3 Find coldest day

In [36]:
arr = np.random.uniform(15.0,45.0,365)
print(arr)
print("Average temprature:",np.mean(arr))
print("Hottest Day:",np.max(arr))
print("Coldest day:",np.min(arr))


[35.73297965 16.73816738 17.18719667 18.22869451 32.10397681 37.8541057
 34.41573947 42.29499724 40.15185383 20.06460601 41.03931417 15.78329847
 26.93205597 32.1748405  32.38139081 15.97336616 44.3764524  17.24940451
 25.62044412 40.226981   27.50164733 29.84133396 44.92982408 37.88998024
 19.51558416 23.52064452 35.66832597 25.18013774 37.7635288  17.69181304
 43.77585753 39.61192597 30.38261156 15.80134192 25.57269268 43.43962213
 22.17670849 37.94173934 43.26504046 16.08096442 30.52675408 25.48767725
 29.05620778 31.33990649 43.71501767 38.05317092 37.43068123 44.26957569
 43.66088844 25.2194484  39.37069677 39.97450397 23.92828207 30.34252329
 37.20603306 33.6719085  37.94724848 36.98442793 34.06323611 38.33447995
 43.27135491 41.38467158 28.79054063 38.16125839 31.98082107 27.82431725
 15.93790443 32.8463839  29.60206812 42.29283341 41.23446737 21.76618114
 24.81977014 19.7550026  23.19289225 37.76134286 15.06459531 21.134287
 34.64579901 36.96742782 42.67810506 30.33821157 41.48

Mini Project 3 — Customer Ratings Generator
Generate
100 customer ratings
Possible values
1,2,3,4,5
Tasks
1 Count how many ratings are 5
2 Calculate average rating

In [38]:
arr = np.random.randint(1, 6, 100)
print(arr)

count_5 = np.sum(arr == 5)
print("Number of 5 star ratings:", count_5)

print("Average rating:", np.mean(arr))

[1 5 5 2 2 3 2 3 2 4 2 3 4 1 5 1 3 3 5 2 4 2 3 3 4 3 3 3 4 5 5 3 3 1 5 5 5
 1 2 1 4 1 2 5 3 1 2 5 4 1 3 1 2 2 4 1 2 1 1 4 5 2 5 4 3 1 5 3 3 4 1 5 1 1
 2 2 3 1 4 5 4 1 2 5 5 4 5 4 4 3 3 5 1 3 3 2 2 3 1 4]
Number of 5 star ratings: 20
Average rating: 2.96


In [ ]:
# Create a NumPy array of numbers 1–20.
# Find its ndim.
# Find its shape.
# Reshape array into 4×5 matrix.
# Flatten the matrix.
# Find total elements using size.
# Check datatype using dtype.
# Find memory usage using nbytes.
# Transpose a 3×3 matrix.
# Convert a 1D array into 2×10 matrix.
arr = np.arange(1,21)
print(arr)
print("*" * 50)
print("\nndim")
print("dimension",np.ndim(arr))
print("*" * 50)
print("\nshape")
print("shape",np.shape(arr))
print("*" * 50)
print("\nreshape")
arr1 = arr.reshape(4,5)
print(arr1)
print("*" * 50)
print("\nflatten")
flat1 = arr1.flatten()
print(flat1)
print("*" * 50)
print("\ntotal element...")
print(arr.size)
print("*" * 50)
print("\ndatatype")
print(arr.dtype)
print("*" * 50)
print("\nmemory usage")
print(arr.nbytes)
print("*" * 50)
print("\ntranspose the matrix")
tra1 = np.transpose(arr1)
print(tra1)
print("*" * 50)
print("\n1D conversion into 2x10 matrix")
arr2 = np.array(arr)
arr2.reshape(2,10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
**************************************************

ndim
dimension 1
**************************************************

shape
shape (20,)
**************************************************

reshape
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
**************************************************

flatten
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
**************************************************

total element...
20
**************************************************

datatype
int64
**************************************************

memory usage
160
**************************************************

transpose the matrix
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
**************************************************

1D conversion into 2x10 matrix


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

Mini Project 1 — Sales Analysis
Dataset
3 products
4 months
Tasks
1 Create array
2 Find
•	shape 
•	size 
•	datatype 
•	memory usage 
3 Transpose dataset

In [ ]:
sales = np.array([
    [100, 120, 130, 140],
    [90, 110, 115, 125],
    [80, 95, 100, 110]
])

print("Sales Data:\n", sales)

print("Shape:", sales.shape)
print("Size:", sales.size)
print("Data Type:", sales.dtype)
print("Memory Usage (bytes):", sales.nbytes)

print("Transposed Data:\n", sales.T)

Sales Data:
 [[100 120 130 140]
 [ 90 110 115 125]
 [ 80  95 100 110]]
Shape: (3, 4)
Size: 12
Data Type: int64
Memory Usage (bytes): 96
Transposed Data:
 [[100  90  80]
 [120 110  95]
 [130 115 100]
 [140 125 110]]


Mini Project 2 — Student Score Dataset
Marks
5 students
3 subjects
Tasks
1 Create dataset
2 Flatten the array
3 Reshape into 3×5

In [68]:
marks = np.array([
    [85, 90, 88],
    [78, 82, 80],
    [92, 95, 94],
    [70, 75, 72],
    [88, 85, 90]
])

print("Marks Data:\n", marks)

flat = marks.flatten()
print("Flattened Array:", flat)

reshaped = flat.reshape(3, 5)
print("Reshaped (3x5):\n", reshaped)

Marks Data:
 [[85 90 88]
 [78 82 80]
 [92 95 94]
 [70 75 72]
 [88 85 90]]
Flattened Array: [85 90 88 78 82 80 92 95 94 70 75 72 88 85 90]
Reshaped (3x5):
 [[85 90 88 78 82]
 [80 92 95 94 70]
 [75 72 88 85 90]]


Mini Project 3 — E-commerce Orders
Generate
20 order values
Tasks
1 Convert into 4×5 matrix
2 Flatten again

In [69]:
orders = np.random.randint(100, 1000, 20)
print("Orders:\n", orders)

matrix = orders.reshape(4, 5)
print("4x5 Matrix:\n", matrix)

flat_orders = matrix.flatten()
print("Flattened Again:\n", flat_orders)

Orders:
 [253 913 228 390 617 620 354 951 667 852 532 527 152 315 246 996 770 156
 912 115]
4x5 Matrix:
 [[253 913 228 390 617]
 [620 354 951 667 852]
 [532 527 152 315 246]
 [996 770 156 912 115]]
Flattened Again:
 [253 913 228 390 617 620 354 951 667 852 532 527 152 315 246 996 770 156
 912 115]


In [85]:
# Create two arrays and add them.
# Multiply an array by 5.
# Subtract two arrays.
# Identify values greater than 100.
# Create boolean array for values <50.
# Increase all prices by 10%.
arr1 = np.array([45,48,892,684])
arr2 = np.array([45,842,486,15])
print("1st array:",arr1)
print("2nd array:",arr2)
print("addition of 2 array:",arr1 + arr2)
print("array multiplied by 5:", arr1 * 5)
print("subtraction of 2 array:",arr1 - arr2)
result = arr1[arr1 > 100]
print("value grater than 100:",result)
print("boolean array for value greater than 50:", arr1 > 50)
print("increased price by 10%:", arr1 + (arr1*0.10))

1st array: [ 45  48 892 684]
2nd array: [ 45 842 486  15]
addition of 2 array: [  90  890 1378  699]
array multiplied by 5: [ 225  240 4460 3420]
subtraction of 2 array: [   0 -794  406  669]
value grater than 100: [892 684]
boolean array for value greater than 50: [False False  True  True]
increased price by 10%: [ 49.5  52.8 981.2 752.4]


In [ ]:
# Use logical AND for two conditions.
arr1 = np.array([45,48,892,684])
arr2 = np.array([45,842,486,15])

arr3 = np.logical_and((arr1 + arr2)>100,(arr1 - arr2)<500)

print(arr3)

[False  True  True False]


In [91]:
# Calculate revenue from price and quantity arrays.
# Find total sales using aggregate operations.
# Identify values greater than average.
price = np.array([100, 200, 300,400])
qty = np.array([10,10,10,10])
rev = price * qty
print(rev)
print("total sales:",np.sum(rev))
arr = price[price > np.mean(price)]
print("price greater than average value",arr)

[1000 2000 3000 4000]
total sales: 10000
price greater than average value [300 400]


Mini Project 1 — Product Revenue Analysis
Dataset
Prices = [100,200,300,400]
Quantity = [5,3,2,4]
Tasks
1 Calculate revenue
2 Identify revenue > 800
3 Increase price by 10%

In [92]:
prices = np.array([100,200,300,400])
quantity = np.array([5,3,2,4])
rev = prices * quantity
arr = rev[rev > 800]
inc_price = prices + (prices*0.10)
print("price:",prices)
print("quantity:",quantity)
print("revenue:",rev)
print("revenue greater than 800:",arr)
print("increased price:",inc_price)

price: [100 200 300 400]
quantity: [5 3 2 4]
revenue: [ 500  600  600 1600]
revenue greater than 800: [1600]
increased price: [110. 220. 330. 440.]


Mini Project 2 — Salary Dataset
Salary
[40000,50000,60000,70000]
Tasks
1 Add bonus of 5000
2 Find employees earning above 60000

In [95]:
salary = np.array([40000,50000,60000,70000])
sal_bonus = salary + 5000
arr = sal_bonus[sal_bonus > 60000]
indices = np.where(sal_bonus > 60000)
print("salary:",salary)
print("salary after bonus:",sal_bonus)
print("employees earning above 60000:", sal_bonus > 60000)
print("employee number of earning above 60000:",indices)
print("employees earning above 60000:", arr)

salary: [40000 50000 60000 70000]
salary after bonus: [45000 55000 65000 75000]
employees earning above 60000: [False False  True  True]
employee number of earning above 60000: (array([2, 3]),)
employees earning above 60000: [65000 75000]


Mini Project 3 — Student Marks System
Marks
[45,67,89,34,78]
Tasks
1 Identify students who passed (>=50)
2 Add grace marks of 5

In [96]:
marks = np.array([45,67,89,34,78])
arr = marks[marks >= 50]
indices = np.where(marks >=50)
grace_mark = marks + 5
print("marks:",marks)
print("passed students:",indices)
print("passed students:",arr)
print("Updated marks:",grace_mark)

marks: [45 67 89 34 78]
passed students: (array([1, 2, 4]),)
passed students: [67 89 78]
Updated marks: [50 72 94 39 83]


In [5]:
# Create an array and compute square root.
# Calculate log10 of values.
arr1 = np.array([45,48,892,684])
print(np.sqrt(arr1))
print(np.log10(arr1))

[ 6.70820393  6.92820323 29.86636905 26.15339366]
[1.65321251 1.68124124 2.95036485 2.8350561 ]


In [6]:
# Multiply two arrays using np.multiply().
arr1 = np.array([45,48,892,684])
arr2 = np.array([45,842,486,15])
print(np.multiply(arr1,arr2))

[  2025  40416 433512  10260]


In [11]:
# Round values to 2 decimal places.
# Compute mean of dataset.
# Compute median of dataset.
# Calculate standard deviation.
# Find maximum and minimum.
# Calculate cumulative sum.
# Find 75th percentile.
arr1 = np.array([6.70820393,6.92820323, 29.86636905, 26.15339366])
print(np.round(arr1,2))
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.cumsum(arr1))
print(np.percentile(arr1,75))

[ 6.71  6.93 29.87 26.15]
17.4140424675
16.540798445
10.677130933551414
6.70820393
29.86636905
[ 6.70820393 13.63640716 43.50277621 69.65616987]
27.081637507499998


Mini Project 1 — Store Sales Analysis
Dataset
sales = [1200,1500,1800,2200,2500,3000]
Tasks
1 Calculate average sales
2 Find median
3 Find standard deviation
4 Find total revenue
5 Find 90th percentile

In [12]:
sales = np.array([1200,1500,1800,2200,2500,3000])
print("\nCalculate average sales:")
print(np.mean(sales))
print("\nFind median:")
print(np.median(sales))
print("\nFind standard deviation:")
print(np.std(sales))
print("\nFind total revenue:")
print(np.sum(sales))
print("\nFind 90th percentile:")
print(np.percentile(sales,90))


Calculate average sales:
2033.3333333333333

Find median:
2000.0

Find standard deviation:
607.3622386096199

Find total revenue:
12200

Find 90th percentile:
2750.0


Mini Project 2 — Student Score Analytics
Marks
[45,67,89,56,72,91,60]
Tasks
1 Average marks
2 Median marks
3 Highest score
4 Lowest score
5 Standard deviation

In [13]:
marks = np.array([45,67,89,56,72,91,60])
print("\naverage marsk:")
print(np.mean(marks))
print("\nFind median:")
print(np.median(marks))
print("\nFind standard deviation:")
print(np.std(marks))
print("\nFind Lowest marsk:")
print(np.min(marks))
print("\nFind Highest score:")
print(np.max(marks))


average marsk:
68.57142857142857

Find median:
67.0

Find standard deviation:
15.683085910415379

Find Lowest marsk:
45

Find Highest score:
91


Mini Project 3 — Customer Purchase Analysis
Purchases
[100,200,300,400,500,600]
Tasks
1 Total purchases
2 Cumulative purchases
3 Average purchase

In [14]:
arr1  = np.array([100,200,300,400,500,600])
print("\naverage marsk:")
print(np.mean(arr1))
print("\nTotal purchases:")
print(np.sum(arr1))
print("\nCumulative purchases:")
print(np.cumsum(arr1))


average marsk:
350.0

Total purchases:
2100

Cumulative purchases:
[ 100  300  600 1000 1500 2100]


In [25]:
# Create array of numbers 1–10.
# Extract element at index 5.
# Extract last element using negative indexing.
# Slice first 5 elements.
# Extract alternate elements using step slicing.
# Filter values greater than 20 using boolean indexing.
# Use np.where() to identify values >20.
arr1  = np.array([0, 3, 6, 9, 12, 15, 18, 21, 24, 27])
print(arr1[5])
print(arr1[-1])
print(arr1[:5])
print(arr1[::2])
print(arr1 > 20)
print(np.where(arr1 > 20))

15
27
[ 0  3  6  9 12]
[ 0  6 12 18 24]
[False False False False False False False  True  True  True]
(array([7, 8, 9]),)


In [31]:
# Create 3×3 matrix and extract second row.
# Extract first column of matrix.
# Use fancy indexing to select elements.
arr1 = np.array([
    [100,200,300],
    [400,500,600],
    [122,233,444]
])

result = arr1[1,2]

print(arr1[1])
print(arr1[0:,0])
print(result)

[400 500 600]
[100 400 122]
600


Mini Project 1 — Sales Filtering
Dataset
sales = [1000,1500,2000,2500,3000]
Tasks
1 Convert into NumPy array
2 Extract sales > 2000
3 Extract first 3 sales

In [35]:
sales = [1000,1500,2000,2500,3000]
arr1 = np.array(sales)
print(arr1)
print(arr1[arr1 > 2000])
print(arr1[:3])

[1000 1500 2000 2500 3000]
[2500 3000]
[1000 1500 2000]


Mini Project 2 — Student Marks Filtering
Marks
[45,67,89,56,34,78]
Tasks
1 Extract students who passed (>=50)
2 Extract top scorers (>80)

In [37]:
marks = np.array([45,67,89,56,34,78])
print("students who passed (>=50)")
print(np.where(marks >= 50))
print(marks[marks >= 50])
print("top scorers (>80)")
print(np.where(marks > 80))
print(marks[marks > 80])

students who passed (>=50)
(array([1, 2, 3, 5]),)
[67 89 56 78]
top scorers (>80)
(array([2]),)
[89]


Mini Project 3 — E-commerce Orders
Orders
[100,200,150,300,400,250]
Tasks
1 Find orders above 250
2 Find their indices using np.where()

In [38]:
orders = np.array([100,200,150,300,400,250])

print(arr1)
print(orders[orders > 250])
print(np.where(orders > 250))

[1000 1500 2000 2500 3000]
[300 400]
(array([3, 4]),)


In [ ]:
arr1 = np.array([45,48,892,684])
arr2 = np.array([45,842,486,15])
print(arr1)
print(arr2)
print("*" * 50)
# Concatenate two arrays.
print(np.concatenate((arr1,arr2)))
print("*" * 50)
# Stack two arrays vertically.
print(np.vstack((arr1,arr2)))
print("*" * 50)
# Stack arrays horizontally.
print(np.hstack((arr1,arr2)))
print("*" * 50)
# Split an array into 4 parts.
print(np.split(arr1,4))


[ 45  48 892 684]
[ 45 842 486  15]
**************************************************
[ 45  48 892 684  45 842 486  15]
**************************************************
[[ 45  48 892 684]
 [ 45 842 486  15]]
**************************************************
[ 45  48 892 684  45 842 486  15]
**************************************************
[array([45]), array([48]), array([892]), array([684])]
**************************************************


In [57]:
arr1 = np.array([45,48,892,684])
arr2 = np.array([45,842,486,15])
print(arr1)
print(arr2)
print("*" * 50)

# Insert value into array.
print("before insert:",arr1)
inst1 = np.insert(arr1,2,50)
print("after insert:",inst1)
print("*" * 50)

# Append value into array.
print("before append:",arr1)
inst2 = np.append(arr1,60)
print("after append:",inst2)
print("*" * 50)

# Delete element at index 3.
print("before Delete:",arr1)
inst3 = np.delete(arr1,3)
print("after Delete:",inst3)
print("*" * 50)

# Create copy of array.
inst3 = arr1.copy()
print(inst3)
print("*" * 50)

# Create view of array.
inst4 = arr1.view()
print(inst4)
print("*" * 50)


[ 45  48 892 684]
[ 45 842 486  15]
**************************************************
before insert: [ 45  48 892 684]
after insert: [ 45  48  50 892 684]
**************************************************
before append: [ 45  48 892 684]
after append: [ 45  48 892 684  60]
**************************************************
before Delete: [ 45  48 892 684]
after Delete: [ 45  48 892]
**************************************************
[ 45  48 892 684]
**************************************************
[ 45  48 892 684]
**************************************************


Mini Project 1 — Sales Dataset Builder
Create arrays:
product_price = [100,200,300]
quantity = [5,3,2]
Tasks:
1 Combine into dataset
2 Add new product using append()
3 Delete product with lowest price

In [11]:
product_price = np.array([100,200,300])
quantity = np.array([5,3,2])
data = np.concatenate((product_price, quantity))
print("combined dataset",data)
arr1 = np.append(product_price,400)
print(arr1)
del1 = np.where(product_price == np.min(product_price))
arr2 = np.delete(product_price,del1)
print(arr2)

combined dataset [100 200 300   5   3   2]
[100 200 300 400]
[200 300]


Mini Project 2 — Student Dataset
Create arrays:
marks = [70,80,90]
attendance = [85,90,95]
Tasks:
1 Combine into matrix
2 Insert new student
3 Split dataset into 2 parts

In [16]:
marks = np.array([70,80,90])
attendance = np.array([85,90,95])
arr1 = np.vstack((marks,attendance))
print(arr1)
new_mark = np.append(marks,65)
new_atten = np.append(attendance,92)
arr2 = np.vstack((new_mark,new_atten))
print(arr2)
print(np.split(arr2,2))

[[70 80 90]
 [85 90 95]]
[[70 80 90 65]
 [85 90 95 92]]
[array([[70, 80, 90, 65]]), array([[85, 90, 95, 92]])]


Mini Project 3 — Customer Features Dataset
Features:
age = [25,30,35]
income = [40000,50000,60000]
spending = [2000,3000,4000]
Tasks:
1 Combine features
2 Split dataset

In [ ]:
age = np.array([25,30,35])
income = np.array([40000,50000,60000])
spending = np.array([2000,3000,4000])
arr1 = np.vstack((age,income,spending))
print(arr1)
print(np.split(arr1,3))

[[   25    30    35]
 [40000 50000 60000]
 [ 2000  3000  4000]]
[array([[25, 30, 35]]), array([[40000, 50000, 60000]]), array([[2000, 3000, 4000]])]


In [42]:
# Remove duplicates from array.
arr1 = np.array([45, 48, 892, 684, 45, 48, 892, 684, 60, 0])
arr3 = np.array([45, 48, 892, 684, 0])
print("array:",arr1)
arr2 = np.unique(arr1)
print("after removing duplicate:",arr2)

# Sort an array.
print(np.sort(arr2))

# Find sorted indices.
print(np.argsort(arr2))

# Replace values using np.where().
new_arr = np.where(arr1 == 892, 69, arr1)
print(new_arr)

# Find non-zero elements.
print(np.nonzero(arr2))

# Check if any value is zero.
print(np.any(arr1,0))

# Check if all values are positive.
print(np.all(arr1 >= 0))

# Detect NaN values.
print(np.isnan(arr3))

# find infinite values.
ar = np.logical_not(np.isfinite(arr1))
print(ar)

# Clip values between 0–100.
print(np.clip(arr1,0,100))

array: [ 45  48 892 684  45  48 892 684  60   0]
after removing duplicate: [  0  45  48  60 684 892]
[  0  45  48  60 684 892]
[0 1 2 3 4 5]
[ 45  48  69 684  45  48  69 684  60   0]
(array([1, 2, 3, 4, 5]),)
True
True
[False False False False False]
[False False False False False False False False False False]
[ 45  48 100 100  45  48 100 100  60   0]


In [25]:
arr1 = np.array([100,200,np.nan,300,400,np.inf,5000])
del_elm = np.where(np.isnan(arr1))
new_arr = np.isfinite(arr1)
final_arr = np.delete(new_arr,del_elm)
print(new_arr)

[ True  True False  True  True False  True]


Mini Project 1 — Customer Data Cleaning 
Dataset [100,200,np.nan,300,400,np.inf,5000] 
Tasks 1 Remove NaN and infinite values 
2 Clip values between 0–1000 
3 Calculate average

In [26]:
arr1 = np.array([100, 200, np.nan, 300, 400, np.inf, 5000])

clean_arr = arr1[np.isfinite(arr1)]
clipped_arr = np.clip(clean_arr, 0, 1000)
average = np.mean(clipped_arr)

print("Original Array:", arr1)
print("Cleaned Array:", clean_arr)
print("Clipped Array:", clipped_arr)
print("Average:", average)

Original Array: [ 100.  200.   nan  300.  400.   inf 5000.]
Cleaned Array: [ 100.  200.  300.  400. 5000.]
Clipped Array: [ 100.  200.  300.  400. 1000.]
Average: 400.0


Mini Project 2 — Product Ratings Analysis
Ratings
[1,2,2,3,4,4,5,5,5]
Tasks
1 Find unique ratings
2 Sort ratings
3 Find indices of sorted array

In [28]:
ratings = np.array([1, 2, 2, 3, 4, 4, 5, 5, 5])
unique_ratings = np.unique(ratings)
sorted_ratings = np.sort(ratings)
sorted_indices = np.argsort(ratings)

print("Original Ratings:", ratings)
print("Unique Ratings:", unique_ratings)
print("Sorted Ratings:", sorted_ratings)
print("Indices of Sorted Array:", sorted_indices)

Original Ratings: [1 2 2 3 4 4 5 5 5]
Unique Ratings: [1 2 3 4 5]
Sorted Ratings: [1 2 2 3 4 4 5 5 5]
Indices of Sorted Array: [0 1 2 3 4 5 6 7 8]


Mini Project 3 — Sales Validation
Sales
[1000,2000,3000,0,500]
Tasks
1 Check if any sale is zero
2 Check if all sales are positive

In [29]:
sales = np.array([1000, 2000, 3000, 0, 500])
any_zero = np.any(sales == 0)
all_positive = np.all(sales > 0)

print("Sales:", sales)
print("Is any sale zero?", any_zero)
print("Are all sales positive?", all_positive)

Sales: [1000 2000 3000    0  500]
Is any sale zero? True
Are all sales positive? False
